services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "https://phoenixnap.dl.sourceforge.net/project/blissos-x86/Official/BlissOS14/FOSS/Surface/Bliss-Surface-v14.10.3-x86_64-OFFICIAL-foss-20241013.iso?viasf=1"
      RAM_SIZE: "12G"
      CPU_CORES: "4"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ./windows:/storage
    restart: always
    stop_grace_period: 2m
